#!/bin/bash
NAMESPACE=$1
j2="j2"

j2 --version > /dev/null
has_j2_rc=$?

if [[ $has_j2_rc -ne 0 ]]; then
    volumes=$(for dir in configmap deployment ing secret svc ${NAMESPACE}; do echo "-v `pwd`/$dir:/$dir"; done)
    j2="docker run $volumes -w / danielpanzella/j2cli"
fi

if [[ -n ${J2_BIN} ]]; then
    j2=${J2_BIN}
fi

for dir in configmap deployment ing secret svc
do
    for f in $(find $dir -type f -name "*.yml")
    do
        mkdir -p $(dirname ${NAMESPACE}/${f})
        $j2 ${f} ${NAMESPACE}/data.yml > ${NAMESPACE}/${f}
    done
done

echo "NOTICE: yaml and secrets created in the clear in $NAMESPACE."
echo "NOTICE: You may need to modify the deployment with appropriate PV and PVC information"
